@url=http://localhost:5000/user

@json=Content-Type: application/json

### 查询
get {{url}}/info

### 注册
post {{url}}/create
{{json}}

{
    "username": "user313",
    "password": "123456",
    "nick": "kiny"
}

## 登录
# post {{url}}/login
# {{json}}

# {
#     "username": "user39",
#     "password": "123456"
# }

### 个人信息
# get {{url}}/profile
# Authorization: Beaere eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFlNzZhYmU5OGRmZGQzZDY5MWViODIiLCJpYXQiOjE1OTU4MzI5MjJ9.kGvDr4hYsO90vKIzyI3I171BS8qMFM9Dl51XxsB1WzE